# Generated by Django 2.2 on 2019-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('place', models.CharField(max_length=55, verbose_name='Место')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
    ]
